vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        categorie:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        sponsor:
            uri_prefix: /images/sponsors
            upload_destination: '%kernel.project_dir%/public/images/sponsors'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        video:
            uri_prefix: /videos
            upload_destination: '%kernel.project_dir%/public/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
